language: ruby

sudo: false

branches:
  except:
    - release

branches:
  only:
    - master
    - develop
    - travis

rvm:
  - 2.1
  - 2.2
  - 2.3

matrix:
  allow_failures:
    - rvm: nightly

addons:
  apt:
    packages:
    - build-essential

before_install:
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;

install:
  - gem install --force bundler
  - bundler install

script:
  - rake test
